package parser;
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

import java.util.ArrayList;
import java.util.List;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\062\000\002\002\004\000\002\002\010\000\002\003" +
    "\004\000\002\003\003\000\002\004\005\000\002\005\003" +
    "\000\002\005\003\000\002\005\003\000\002\006\004\000" +
    "\002\006\003\000\002\007\003\000\002\007\003\000\002" +
    "\007\003\000\002\007\003\000\002\007\003\000\002\010" +
    "\005\000\002\011\004\000\002\011\004\000\002\012\012" +
    "\000\002\013\015\000\002\013\011\000\002\014\005\000" +
    "\002\014\005\000\002\014\003\000\002\015\005\000\002" +
    "\015\005\000\002\015\003\000\002\016\003\000\002\016" +
    "\003\000\002\016\003\000\002\016\003\000\002\016\005" +
    "\000\002\016\003\000\002\017\005\000\002\017\005\000" +
    "\002\017\005\000\002\017\005\000\002\017\005\000\002" +
    "\017\005\000\002\020\005\000\002\020\005\000\002\021" +
    "\013\000\002\022\005\000\002\022\003\000\002\023\003" +
    "\000\002\023\003\000\002\024\003\000\002\024\003\000" +
    "\002\024\003\000\002\024\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\147\000\004\004\004\001\002\000\004\047\007\001" +
    "\002\000\004\002\006\001\002\000\004\002\001\001\002" +
    "\000\004\036\145\001\002\000\006\005\013\047\007\001" +
    "\002\000\006\005\ufffe\047\ufffe\001\002\000\006\005\uffff" +
    "\047\uffff\001\002\000\004\006\014\001\002\000\014\010" +
    "\025\011\024\012\016\014\022\047\023\001\002\000\020" +
    "\007\ufff4\010\ufff4\011\ufff4\012\ufff4\014\ufff4\044\ufff4\047" +
    "\ufff4\001\002\000\004\043\136\001\002\000\020\007\ufff3" +
    "\010\ufff3\011\ufff3\012\ufff3\014\ufff3\044\ufff3\047\ufff3\001" +
    "\002\000\020\007\ufff5\010\ufff5\011\ufff5\012\ufff5\014\ufff5" +
    "\044\ufff5\047\ufff5\001\002\000\020\007\ufff8\010\ufff8\011" +
    "\ufff8\012\ufff8\014\ufff8\044\ufff8\047\ufff8\001\002\000\004" +
    "\041\102\001\002\000\004\035\100\001\002\000\004\041" +
    "\041\001\002\000\014\047\033\050\037\051\036\052\035" +
    "\053\034\001\002\000\020\007\ufff6\010\ufff6\011\ufff6\012" +
    "\ufff6\014\ufff6\044\ufff6\047\ufff6\001\002\000\016\007\031" +
    "\010\025\011\024\012\016\014\022\047\023\001\002\000" +
    "\020\007\ufff7\010\ufff7\011\ufff7\012\ufff7\014\ufff7\044\ufff7" +
    "\047\ufff7\001\002\000\004\002\000\001\002\000\020\007" +
    "\ufff9\010\ufff9\011\ufff9\012\ufff9\014\ufff9\044\ufff9\047\ufff9" +
    "\001\002\000\020\007\ufff0\010\ufff0\011\ufff0\012\ufff0\014" +
    "\ufff0\044\ufff0\047\ufff0\001\002\000\022\007\uffd0\010\uffd0" +
    "\011\uffd0\012\uffd0\014\uffd0\040\uffd0\044\uffd0\047\uffd0\001" +
    "\002\000\022\007\uffd1\010\uffd1\011\uffd1\012\uffd1\014\uffd1" +
    "\040\uffd1\044\uffd1\047\uffd1\001\002\000\022\007\uffd2\010" +
    "\uffd2\011\uffd2\012\uffd2\014\uffd2\040\uffd2\044\uffd2\047\uffd2" +
    "\001\002\000\022\007\uffd3\010\uffd3\011\uffd3\012\uffd3\014" +
    "\uffd3\040\uffd3\044\uffd3\047\uffd3\001\002\000\020\007\ufff1" +
    "\010\ufff1\011\ufff1\012\ufff1\014\ufff1\044\ufff1\047\ufff1\001" +
    "\002\000\006\021\044\023\043\001\002\000\012\050\037" +
    "\051\036\052\035\053\034\001\002\000\012\050\uffd4\051" +
    "\uffd4\052\uffd4\053\uffd4\001\002\000\012\050\uffd5\051\uffd5" +
    "\052\uffd5\053\uffd5\001\002\000\004\040\046\001\002\000" +
    "\004\045\047\001\002\000\016\011\024\041\061\047\056" +
    "\050\055\051\053\053\052\001\002\000\056\007\uffe1\010" +
    "\uffe1\011\uffe1\012\uffe1\014\uffe1\021\uffe1\022\uffe1\023\uffe1" +
    "\024\uffe1\025\uffe1\026\uffe1\027\uffe1\030\uffe1\031\uffe1\032" +
    "\uffe1\033\uffe1\034\uffe1\040\uffe1\042\uffe1\044\uffe1\046\uffe1" +
    "\047\uffe1\001\002\000\056\007\uffea\010\uffea\011\uffea\012" +
    "\uffea\014\uffea\021\uffea\022\uffea\023\067\024\070\025\uffea" +
    "\026\uffea\027\uffea\030\uffea\031\uffea\032\uffea\033\uffea\034" +
    "\uffea\040\uffea\042\uffea\044\uffea\046\uffea\047\uffea\001\002" +
    "\000\056\007\uffe3\010\uffe3\011\uffe3\012\uffe3\014\uffe3\021" +
    "\uffe3\022\uffe3\023\uffe3\024\uffe3\025\uffe3\026\uffe3\027\uffe3" +
    "\030\uffe3\031\uffe3\032\uffe3\033\uffe3\034\uffe3\040\uffe3\042" +
    "\uffe3\044\uffe3\046\uffe3\047\uffe3\001\002\000\056\007\uffe5" +
    "\010\uffe5\011\uffe5\012\uffe5\014\uffe5\021\uffe5\022\uffe5\023" +
    "\uffe5\024\uffe5\025\uffe5\026\uffe5\027\uffe5\030\uffe5\031\uffe5" +
    "\032\uffe5\033\uffe5\034\uffe5\040\uffe5\042\uffe5\044\uffe5\046" +
    "\uffe5\047\uffe5\001\002\000\012\021\064\022\065\040\uffd6" +
    "\046\uffd6\001\002\000\056\007\uffe4\010\uffe4\011\uffe4\012" +
    "\uffe4\014\uffe4\021\uffe4\022\uffe4\023\uffe4\024\uffe4\025\uffe4" +
    "\026\uffe4\027\uffe4\030\uffe4\031\uffe4\032\uffe4\033\uffe4\034" +
    "\uffe4\040\uffe4\042\uffe4\044\uffe4\046\uffe4\047\uffe4\001\002" +
    "\000\056\007\uffe6\010\uffe6\011\uffe6\012\uffe6\014\uffe6\021" +
    "\uffe6\022\uffe6\023\uffe6\024\uffe6\025\uffe6\026\uffe6\027\uffe6" +
    "\030\uffe6\031\uffe6\032\uffe6\033\uffe6\034\uffe6\040\uffe6\042" +
    "\uffe6\044\uffe6\046\uffe6\047\uffe6\001\002\000\056\007\uffe7" +
    "\010\uffe7\011\uffe7\012\uffe7\014\uffe7\021\uffe7\022\uffe7\023" +
    "\uffe7\024\uffe7\025\uffe7\026\uffe7\027\uffe7\030\uffe7\031\uffe7" +
    "\032\uffe7\033\uffe7\034\uffe7\040\uffe7\042\uffe7\044\uffe7\046" +
    "\uffe7\047\uffe7\001\002\000\006\040\074\046\075\001\002" +
    "\000\016\011\024\041\061\047\056\050\055\051\053\053" +
    "\052\001\002\000\010\021\064\022\065\042\063\001\002" +
    "\000\056\007\uffe2\010\uffe2\011\uffe2\012\uffe2\014\uffe2\021" +
    "\uffe2\022\uffe2\023\uffe2\024\uffe2\025\uffe2\026\uffe2\027\uffe2" +
    "\030\uffe2\031\uffe2\032\uffe2\033\uffe2\034\uffe2\040\uffe2\042" +
    "\uffe2\044\uffe2\046\uffe2\047\uffe2\001\002\000\016\011\024" +
    "\041\061\047\056\050\055\051\053\053\052\001\002\000" +
    "\016\011\024\041\061\047\056\050\055\051\053\053\052" +
    "\001\002\000\056\007\uffeb\010\uffeb\011\uffeb\012\uffeb\014" +
    "\uffeb\021\uffeb\022\uffeb\023\067\024\070\025\uffeb\026\uffeb" +
    "\027\uffeb\030\uffeb\031\uffeb\032\uffeb\033\uffeb\034\uffeb\040" +
    "\uffeb\042\uffeb\044\uffeb\046\uffeb\047\uffeb\001\002\000\016" +
    "\011\024\041\061\047\056\050\055\051\053\053\052\001" +
    "\002\000\016\011\024\041\061\047\056\050\055\051\053" +
    "\053\052\001\002\000\056\007\uffe8\010\uffe8\011\uffe8\012" +
    "\uffe8\014\uffe8\021\uffe8\022\uffe8\023\uffe8\024\uffe8\025\uffe8" +
    "\026\uffe8\027\uffe8\030\uffe8\031\uffe8\032\uffe8\033\uffe8\034" +
    "\uffe8\040\uffe8\042\uffe8\044\uffe8\046\uffe8\047\uffe8\001\002" +
    "\000\056\007\uffe9\010\uffe9\011\uffe9\012\uffe9\014\uffe9\021" +
    "\uffe9\022\uffe9\023\uffe9\024\uffe9\025\uffe9\026\uffe9\027\uffe9" +
    "\030\uffe9\031\uffe9\032\uffe9\033\uffe9\034\uffe9\040\uffe9\042" +
    "\uffe9\044\uffe9\046\uffe9\047\uffe9\001\002\000\056\007\uffec" +
    "\010\uffec\011\uffec\012\uffec\014\uffec\021\uffec\022\uffec\023" +
    "\067\024\070\025\uffec\026\uffec\027\uffec\030\uffec\031\uffec" +
    "\032\uffec\033\uffec\034\uffec\040\uffec\042\uffec\044\uffec\046" +
    "\uffec\047\uffec\001\002\000\016\011\024\041\061\047\056" +
    "\050\055\051\053\053\052\001\002\000\004\042\076\001" +
    "\002\000\056\007\uffd8\010\uffd8\011\uffd8\012\uffd8\014\uffd8" +
    "\021\uffd8\022\uffd8\023\uffd8\024\uffd8\025\uffd8\026\uffd8\027" +
    "\uffd8\030\uffd8\031\uffd8\032\uffd8\033\uffd8\034\uffd8\040\uffd8" +
    "\042\uffd8\044\uffd8\046\uffd8\047\uffd8\001\002\000\012\021" +
    "\064\022\065\040\uffd7\046\uffd7\001\002\000\016\011\024" +
    "\041\061\047\056\050\055\051\053\053\052\001\002\000" +
    "\024\007\ufff2\010\ufff2\011\ufff2\012\ufff2\014\ufff2\021\064" +
    "\022\065\044\ufff2\047\ufff2\001\002\000\016\011\024\041" +
    "\061\047\056\050\055\051\053\053\052\001\002\000\006" +
    "\033\132\034\133\001\002\000\022\021\064\022\065\025" +
    "\122\026\123\027\117\030\120\031\121\032\116\001\002" +
    "\000\004\042\106\001\002\000\004\043\107\001\002\000" +
    "\014\010\025\011\024\012\016\014\022\047\023\001\002" +
    "\000\016\010\025\011\024\012\016\014\022\044\111\047" +
    "\023\001\002\000\022\007\uffed\010\uffed\011\uffed\012\uffed" +
    "\014\uffed\015\112\044\uffed\047\uffed\001\002\000\004\043" +
    "\113\001\002\000\014\010\025\011\024\012\016\014\022" +
    "\047\023\001\002\000\016\010\025\011\024\012\016\014" +
    "\022\044\115\047\023\001\002\000\020\007\uffee\010\uffee" +
    "\011\uffee\012\uffee\014\uffee\044\uffee\047\uffee\001\002\000" +
    "\016\011\024\041\061\047\056\050\055\051\053\053\052" +
    "\001\002\000\016\011\024\041\061\047\056\050\055\051" +
    "\053\053\052\001\002\000\016\011\024\041\061\047\056" +
    "\050\055\051\053\053\052\001\002\000\016\011\024\041" +
    "\061\047\056\050\055\051\053\053\052\001\002\000\016" +
    "\011\024\041\061\047\056\050\055\051\053\053\052\001" +
    "\002\000\016\011\024\041\061\047\056\050\055\051\053" +
    "\053\052\001\002\000\014\021\064\022\065\033\uffdb\034" +
    "\uffdb\042\uffdb\001\002\000\014\021\064\022\065\033\uffdc" +
    "\034\uffdc\042\uffdc\001\002\000\014\021\064\022\065\033" +
    "\uffe0\034\uffe0\042\uffe0\001\002\000\014\021\064\022\065" +
    "\033\uffdd\034\uffdd\042\uffdd\001\002\000\014\021\064\022" +
    "\065\033\uffde\034\uffde\042\uffde\001\002\000\014\021\064" +
    "\022\065\033\uffdf\034\uffdf\042\uffdf\001\002\000\016\011" +
    "\024\041\061\047\056\050\055\051\053\053\052\001\002" +
    "\000\016\011\024\041\061\047\056\050\055\051\053\053" +
    "\052\001\002\000\004\042\uffd9\001\002\000\004\042\uffda" +
    "\001\002\000\014\010\025\011\024\012\016\014\022\047" +
    "\023\001\002\000\016\010\025\011\024\012\016\014\022" +
    "\044\140\047\023\001\002\000\004\013\141\001\002\000" +
    "\004\041\142\001\002\000\016\011\024\041\061\047\056" +
    "\050\055\051\053\053\052\001\002\000\004\042\144\001" +
    "\002\000\020\007\uffef\010\uffef\011\uffef\012\uffef\014\uffef" +
    "\044\uffef\047\uffef\001\002\000\010\016\151\017\150\020" +
    "\146\001\002\000\006\005\ufffa\047\ufffa\001\002\000\006" +
    "\005\ufffd\047\ufffd\001\002\000\006\005\ufffb\047\ufffb\001" +
    "\002\000\006\005\ufffc\047\ufffc\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\147\000\004\002\004\001\001\000\006\003\007\004" +
    "\010\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\004\011\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\020\006\026\007\020" +
    "\010\027\011\025\012\017\013\014\021\016\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\024\037\001\001\000\002" +
    "\001\001\000\016\007\031\010\027\011\025\012\017\013" +
    "\014\021\016\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\023\041\001\001\000\004\024\044\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\014\014\053\015\050\016\056\021" +
    "\047\022\057\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\012\014\061\015\050\016\056\021\047\001" +
    "\001\000\002\001\001\000\002\001\001\000\010\015\072" +
    "\016\056\021\047\001\001\000\010\015\065\016\056\021" +
    "\047\001\001\000\002\001\001\000\006\016\071\021\047" +
    "\001\001\000\006\016\070\021\047\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\012\014\076" +
    "\015\050\016\056\021\047\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\012\014\100\015\050" +
    "\016\056\021\047\001\001\000\002\001\001\000\016\014" +
    "\103\015\050\016\056\017\102\020\104\021\047\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\020\006\107\007\020\010\027\011\025" +
    "\012\017\013\014\021\016\001\001\000\016\007\031\010" +
    "\027\011\025\012\017\013\014\021\016\001\001\000\002" +
    "\001\001\000\002\001\001\000\020\006\113\007\020\010" +
    "\027\011\025\012\017\013\014\021\016\001\001\000\016" +
    "\007\031\010\027\011\025\012\017\013\014\021\016\001" +
    "\001\000\002\001\001\000\012\014\130\015\050\016\056" +
    "\021\047\001\001\000\012\014\127\015\050\016\056\021" +
    "\047\001\001\000\012\014\126\015\050\016\056\021\047" +
    "\001\001\000\012\014\125\015\050\016\056\021\047\001" +
    "\001\000\012\014\124\015\050\016\056\021\047\001\001" +
    "\000\012\014\123\015\050\016\056\021\047\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\014\014" +
    "\103\015\050\016\056\017\134\021\047\001\001\000\014" +
    "\014\103\015\050\016\056\017\133\021\047\001\001\000" +
    "\002\001\001\000\002\001\001\000\020\006\136\007\020" +
    "\010\027\011\025\012\017\013\014\021\016\001\001\000" +
    "\016\007\031\010\027\011\025\012\017\013\014\021\016" +
    "\001\001\000\002\001\001\000\002\001\001\000\016\014" +
    "\103\015\050\016\056\017\102\020\142\021\047\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\005\146\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    private List<String> reglasAplicadas = new ArrayList<>();

    public List<String> getReglasAplicadas() {
        return reglasAplicadas;
    }

    public void report_error(String message, Object info) {
        System.err.println("Error: " + message);
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // programa ::= DECVAR declaraciones ENDDECVAR PROGRAM_SECTION sentencias ENDPROGRAM_SECTION 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 1] programa → DECVAR declaraciones ENDDECVAR PROGRAM_SECTION sentencias ENDPROGRAM_SECTION"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // declaraciones ::= declaraciones declaracion 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 2] declaraciones → declaraciones declaracion"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaraciones",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // declaraciones ::= declaracion 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 3] declaraciones → declaracion"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaraciones",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // declaracion ::= ID COLON tipo 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 4] declaracion → ID COLON tipo"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaracion",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // tipo ::= INT 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 5] tipo → INT"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // tipo ::= FLOAT 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 6] tipo → FLOAT"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // tipo ::= STRING 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 7] tipo → STRING"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // sentencias ::= sentencias sentencia 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 8] sentencias → sentencias sentencia"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencias",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // sentencias ::= sentencia 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 9] sentencias → sentencia"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencias",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // sentencia ::= assign 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 10] sentencia → assign"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // sentencia ::= escritura 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 11] sentencia → escritura"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // sentencia ::= repeat 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 12] sentencia → repeat"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // sentencia ::= if 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 13] sentencia → if"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // sentencia ::= map 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 50] expresion → map"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // assign ::= ID ASSIGN expresion 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 14] assign → ID ASSIGN expresion"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("assign",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // escritura ::= SHOW cte 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 15] escritura → SHOW cte"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("escritura",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // escritura ::= SHOW ID 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 16] escritura → SHOW ID"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("escritura",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // repeat ::= REPEAT LBRACE sentencias RBRACE UNTIL LPAREN condicion RPAREN 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 17] repeat → REPEAT LBRACE sentencias RBRACE UNTIL LPAREN condicion RPAREN"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("repeat",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // if ::= IF LPAREN condicion RPAREN LBRACE sentencias RBRACE ELSE LBRACE sentencias RBRACE 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 18] if → IF LPAREN condicion RPAREN LBRACE sentencias RBRACE ELSE LBRACE sentencias RBRACE"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("if",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-10)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // if ::= IF LPAREN condicion RPAREN LBRACE sentencias RBRACE 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 19] if → IF LPAREN condicion RPAREN LBRACE sentencias RBRACE"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("if",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // expresion ::= expresion PLUS termino 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 20] expresion → expresion PLUS termino"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // expresion ::= expresion MINUS termino 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 21] expresion → expresion MINUS termino"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // expresion ::= termino 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 22] expresion → termino"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // termino ::= termino MULT factor 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 23] termino → termino MULT factor"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("termino",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // termino ::= termino DIV factor 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 24] termino → termino DIV factor"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("termino",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // termino ::= factor 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 25] termino → factor"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("termino",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // factor ::= ID 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 26] factor → ID"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // factor ::= CONST_FLOAT 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 27] factor → CONST_FLOAT"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // factor ::= CONST_INT 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 28] factor → CONST_INT"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // factor ::= CONST_HEX 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 29] factor → CONST_HEX"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // factor ::= LPAREN expresion RPAREN 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 30] factor → LPAREN expresion RPAREN"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // factor ::= map 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 31] factor → map"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // comparacion ::= expresion EQUAL expresion 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 32] comparacion → expresion EQUAL expresion"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparacion",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // comparacion ::= expresion NOT_EQUAL expresion 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 33] comparacion → expresion NOT_EQUAL expresion"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparacion",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // comparacion ::= expresion GREATER expresion 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 34] comparacion → expresion GREATER expresion"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparacion",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // comparacion ::= expresion GREATER_EQUAL expresion 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 35] comparacion → expresion GREATER_EQUAL expresion"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparacion",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // comparacion ::= expresion LESS expresion 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 36] comparacion → expresion LESS expresion"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparacion",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // comparacion ::= expresion LESS_EQUAL expresion 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 37] comparacion → expresion LESS_EQUAL expresion"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparacion",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // condicion ::= comparacion AND comparacion 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 38] condicion → comparacion AND comparacion"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // condicion ::= comparacion OR comparacion 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 39] condicion → comparacion OR comparacion"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // map ::= MAP LPAREN operador cte COMMA LBRACKET lista_expresiones RBRACKET RPAREN 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 41] map → MAP LPAREN operador cte COMMA LBRACKET lista_expresiones RBRACKET RPAREN"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("map",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-8)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // lista_expresiones ::= lista_expresiones COMMA expresion 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 42] lista_expresiones → lista_expresiones COMMA expresion"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_expresiones",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // lista_expresiones ::= expresion 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 43] lista_expresiones → expresion"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_expresiones",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // operador ::= PLUS 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 44] operador → PLUS"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("operador",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // operador ::= MULT 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 45] operador → MULT"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("operador",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // cte ::= CONST_INT 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 46] cte → CONST_INT"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("cte",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // cte ::= CONST_FLOAT 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 47] cte → CONST_FLOAT"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("cte",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // cte ::= CONST_STRING 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 48] cte → CONST_STRING"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("cte",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // cte ::= CONST_HEX 
            {
              Object RESULT =null;
		 reglasAplicadas.add("[Regla 49] cte → CONST_HEX"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("cte",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
