package parser;
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAP = 7;
  public static final int SHOW = 6;
  public static final int LBRACKET = 31;
  public static final int MULT = 14;
  public static final int NOT_EQUAL = 21;
  public static final int LPAREN = 27;
  public static final int GREATER = 18;
  public static final int REPEAT = 8;
  public static final int INT = 38;
  public static final int LESS = 16;
  public static final int MINUS = 13;
  public static final int RPAREN = 28;
  public static final int AND = 22;
  public static final int ENDDECVAR = 3;
  public static final int OR = 23;
  public static final int COMMA = 26;
  public static final int DIV = 15;
  public static final int UNTIL = 9;
  public static final int LESS_EQUAL = 17;
  public static final int CONST_FLOAT = 34;
  public static final int PLUS = 12;
  public static final int ASSIGN = 24;
  public static final int IF = 10;
  public static final int ID = 37;
  public static final int EOF = 0;
  public static final int RBRACKET = 32;
  public static final int EQUAL = 20;
  public static final int GREATER_EQUAL = 19;
  public static final int error = 1;
  public static final int DECVAR = 2;
  public static final int COLON = 25;
  public static final int LBRACE = 29;
  public static final int ELSE = 11;
  public static final int FLOAT = 39;
  public static final int RBRACE = 30;
  public static final int CONST_STRING = 35;
  public static final int PROGRAM_SECTION = 4;
  public static final int STRING = 40;
  public static final int ENDPROGRAM_SECTION = 5;
  public static final int CONST_INT = 33;
  public static final int CONST_HEX = 36;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DECVAR",
  "ENDDECVAR",
  "PROGRAM_SECTION",
  "ENDPROGRAM_SECTION",
  "SHOW",
  "MAP",
  "REPEAT",
  "UNTIL",
  "IF",
  "ELSE",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "LESS",
  "LESS_EQUAL",
  "GREATER",
  "GREATER_EQUAL",
  "EQUAL",
  "NOT_EQUAL",
  "AND",
  "OR",
  "ASSIGN",
  "COLON",
  "COMMA",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "LBRACKET",
  "RBRACKET",
  "CONST_INT",
  "CONST_FLOAT",
  "CONST_STRING",
  "CONST_HEX",
  "ID",
  "INT",
  "FLOAT",
  "STRING"
  };
}

